import { Expr } from './ll-parser'
import { Either } from './utils'

export const BUILTINS: {[keys: string]: boolean} = {
  'add': true,
  'sub': true,
  'mul': true,
  'div': true,
  'mod': true,
  'band': true,
  'bor': true,
  'bxor': true,
  'bcom': true,
  '<<': true,
  '>>': true,
  '#t': true,
  '#f': true,
  '=': true,
  '!=': true,
  'lt': true,
  'gt': true,
  'le': true,
  'ge': true,
  '#int': true,
  'trunc': true,
  'floor': true,
  'ceil': true,
  'round': true,
  'abs': true,
  'show': true,
  'parse': true,
  'chars': true,
  'len': true,
  'head': true,
  'tail': true,
  'front': true,
  'last': true,
  'get': true,
  'tryget': true,
  'set': true,
  'tryset': true,
  'keys': true,
  'entries': true,
  'push': true,
  'pop': true,
  'push-front': true,
  'pop-front': true,
}

// function evaluate(expr: Expr): Either<Value, string> {
// }
